export enum TokenTypes {
  FORGOT = "FORGOT PASSWORD",
  REGISTRATION = "REGISTRATION",
  VERIFICATION = "VERIFICATION",
  "2FA" = "TWO FACTOR AUTHENTICATION",
}

export enum UserRoles {
  LOGS = "LOGS",
  USER = "USER",
  ADMIN = "ADMIN",
}
